// Generated by CoffeeScript 1.12.2
(function() {
  "use strict";
  var hljs;

  hljs = require('highlight.js');

  module.exports = function(md, opts) {
    var autoLanguage, existing_highlight;
    if ((opts != null ? opts.classPrefix : void 0) != null) {
      hljs.configure({
        classPrefix: opts.classPrefix
      });
    }
    autoLanguage = opts != null ? opts.autoLanguage : void 0;
    existing_highlight = md.options.highlight;
    return md.options.highlight = function(str, lang) {
      if (lang && hljs.getLanguage(lang)) {
        try {
          return hljs.highlight(lang, str).value;
        } catch (error) {}
      }
      if (autoLanguage) {
        try {
          return hljs.highlightAuto(str).value;
        } catch (error) {}
      }
      if (existing_highlight) {
        return existing_highlight(str, lang);
      }
      return '';
    };
  };

}).call(this);

//# sourceMappingURL=highlight.js.map
