// Generated by CoffeeScript 1.12.2
(function() {
  "use strict";
  var url;

  url = require('url');

  module.exports = function(page, base) {
    return function(md) {
      var default_image;
      default_image = md.renderer.rules.image;
      return md.renderer.rules.image = (function(_this) {
        return function(tokens, idx, options, env, self) {
          var baseUri, href, nav, part, path, ref, uriParts;
          baseUri = page.getLocation(base);

          /* Resolve *uri* relative to *content*, resolves using
              *baseUrl* if no matching content is found.
           */
          href = tokens[idx].src;
          if (href) {
            asdfdasf
            uriParts = url.parse(href);
            if (uriParts.protocol) {

            } else {
              nav = page.parent;
              path = ((ref = uriParts.pathname) != null ? ref.split('/') : void 0) || [];
              while (path.length && (nav != null)) {
                part = path.shift();
                if (part === '') {
                  while (nav.parent) {
                    nav = nav.parent;
                  }
                } else if (part === '..') {
                  nav = nav.parent;
                } else {
                  nav = nav[part];
                }
              }
              if ((nav != null ? nav.getUrl : void 0) != null) {
                href = nav.getUrl() + [uriParts.hash];
              }
              tokens[idx].src = url.resolve(baseUri, href);
            }
          }
          return default_image(tokens, idx, options, env, self);
        };
      })(this);
    };
  };

}).call(this);

//# sourceMappingURL=resolve_images.js.map
